version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: "Europe/Paris"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 50
    rebase-strategy: disabled
